const actionTypes = {
  //hastalar
  FETCH_HASTALAR_START: " FETCH_HASTALAR_START",
  FETCH_HASTALAR_SUCCESS: " FETCH_HASTALAR_SUCCESS",
  FETCH_HASTALAR_FAIL: " FETCH_HASTALAR_FAIL",
  ADD_HASTA: "ADD_HASTA",
  DELETE_HASTA: "DELETE_HASTA",
  EDİT_HASTA: "EDIT_HASTA",
  //randevular
  FETCH_RANDEVULAR_START: " FETCH_RANDEVULAR_START",
  FETCH_RANDEVULAR_SUCCESS: " FETCH_RANDEVULAR_SUCCESS",
  FETCH_RANDEVULAR_FAIL: " FETCH_RANDEVULAR_FAIL",
  ADD_RANDEVU: "ADD_RANDEVU",
  DELETE_RANDEVU: "DELETE_RANDEVU",
  EDİT_RANDEVU: "EDIT_RANDEVU",
  //islemler
  FETCH_ISLEMLER_START: " FETCH_SLEMLER_START",
  FETCH_ISLEMLER_SUCCESS: " FETCH_ISLEMLER_SUCCESS",
  FETCH_ISLEMLER_FAIL: " FETCH_ISLEMLER_FAIL",
  ADD_ISLEM: "ADD_ISLEM",
  DELETE_ISLEM: "DELETE_ISLEM",
  EDİT_ISLEM: "EDIT_ISLEM",
};

export default actionTypes;
